# @Author: Matthew Hale <mlhale>
# @Date:   2018-02-14T23:02:38-06:00
# @Email:  mlhale@unomaha.edu
# @Filename: docker-compose.yml
# @Last modified by:   mlhale
# @Last modified time: 2018-02-15T00:22:08-06:00
# @License: Funset is a web-based BIOI tool for visualizing genetic pathway information. This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
# @Copyright: Copyright (C) 2017 Matthew L. Hale, Dario Ghersi, Ishwor Thapa



version: "3"
services:
  db:
    restart: always
    image: postgres
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
      - ./database-backup:/database-backup
  django:
    build: ../.
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py migrate && python /var/www/backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../backend:/var/www/backend
      - ../GOUtil:/GOUtil
      - ../GOUtildata:/GOUtildata
    ports:
     - "80:8000"
    depends_on:
     - db
volumes:
  postgres-config:
  postgres-data:
  postgres-logs:
